### ISSUE TITLE
make keyword?

### ISSUE THREAD

**Issue by djzort** [RexOps/rexify-website#160]
In this guide https://github.com/RexOps/rexify-website/blob/master/content/docs/rex_book/infrastructure/example_of_a_complete_rex_code_infrastructure.md

there is a keyword "make" that doesnt seem to appear anywhere else

could its function be clarified?

**Comment by krimdomu** [comment]
The `make` keyword was added because of a joke. A colleague of mine loved the `make` tool so he wrote everything in makefiles ;-)

It is just a replacement for `sub`. So it just creates an anonymous function.

This is the code inside Rex::Commands:

```
sub make(&) {
  return $_[0];
}
```

**Comment by ferki** [comment]
Thanks for this question as well, @djzort! And for the insights about the origin story of `make`, @krimdomu! :)

**Comment by djzort** [comment]
It might be a good idea to remove it from the documentation.

**Comment by ferki** [comment]
> It might be a good idea to remove it from the documentation.

The Rex documentation lives in the RexOps/Rex repo together with the code (and released to CPAN). In order to not break backwards compatibility, we can't remove `make` quickly from the API, but we could add some documentation for it there, and perhaps also add a deprecation notice later if we deem it should go away in a later major release.

As far as the guides and the "Rex book" on the website are concerned, it might help to think of those as more of "a collection of articles written by various people across years", instead of "documentation". Most of those authors don't maintain the content actively here anymore, so I considered moving them into an "archive" section to make that explicit, and also display the original author and last modification date of each page (see #155).
